hmrc/platsec-ci-terraform

main.tf, modules/lambda_docker_pipeline/variables.tf, modules/lambda_zip_pipeline/iam.tf, modules/lambda_zip_pipeline/variables.tf
Co-authored-by: Cormac Brady: <public+github@cormacbrady.info>
=> PSEC-1329 Remove github connection

data.tf, main.tf, modules/ecs_task_pipeline/README.md, modules/ecs_task_pipeline/build.tf, modules/ecs_task_pipeline/github_webhook.tf, modules/ecs_task_pipeline/iam.tf, modules/ecs_task_pipeline/main.tf, modules/ecs_task_pipeline/pipeline.tf, modules/ecs_task_pipeline/s3.tf, modules/ecs_task_pipeline/variables.tf, modules/lambda_zip_pipeline/build.tf, modules/lambda_zip_pipeline/variables.tf, modules/update_task_definition_step/assets/buildspec-deploy.yaml, modules/update_task_definition_step/codebuild.tf, modules/update_task_definition_step/iam.tf, modules/update_task_definition_step/main.tf, modules/update_task_definition_step/outputs.tf, modules/update_task_definition_step/variables.tf
add ecs_task_pipeline pipeline type
use different roles with limited permissions for steps that interact
with different aws services
=> PSEC-1416 add compliance-dataviz pipeline

modules/git_tag_step/assets/git-tag.yaml
display request and response documents to ease trouble shooting
=> PSEC-1408 test success field in response to git tag request

modules/git_version_step/assets/git-version.yaml, modules/git_version_step/codebuild.tf, modules/git_version_step/variables.tf, modules/terraform_module_pipeline/build.tf, modules/terraform_module_pipeline/pipeline.tf
=> PSEC-1472 respect GitVersion config

pipelines.tf
Signed-off-by: Tom Roffe <tom@altobyte.io>
=> Add github-admin-tool pipeline

.gitignore, modules/platsec_terraform_pipeline/build.tf, modules/platsec_terraform_pipeline/buildspecs/apply.yaml.tpl, modules/platsec_terraform_pipeline/iam.tf, modules/platsec_terraform_pipeline/main.tf, modules/platsec_terraform_pipeline/pipeline.tf, modules/platsec_terraform_pipeline/variables.tf, modules/terraform_step/codebuild.tf, modules/terraform_step/iam.tf, modules/terraform_step/outputs.tf, modules/terraform_step/variables.tf, pipelines.tf
New pipeline for platsec-terraform repo
=> PSEC-1697-platsec-terraform-pipeline

main.tf, pipelines.tf, pull_request_builder.tf
Env vars for TFApplier and TFPlanner roles
=> PSEC-1868-tf-automation-role-env-vars

pipelines.tf, pull_request_builder.tf
Disable use of TFProvisioner role for platsec-terraform CI
=> PSEC-1868-remove-platsec-tfprovisioner

.remarkrc, Makefile, README.md, bootstrap/README.md, ecr_repositories.tf, main.tf, modules/ecs_task_pipeline/README.md, modules/lambda_docker_pipeline/README.md, modules/lambda_zip_pipeline/README.md, modules/sandbox_lambda_docker_pipeline/README.md, modules/service_endpoint_connector/README.md, modules/terraform_module_pipeline/README.md, pipelines.tf
- Use new pattern on cloudtrail-monitoring to dockerise publishing
- Make use of ECR
- Stop publishing via brittle Jenkins
- Fix MD linting failures
- Jenkins publish was broken, i'd rather fix forward than backwards
- Consistency
- I hate lots of linting warning
<details>
<summary>Click to toggle contents of `make plan`</summary>
```
~ resource "aws_codepipeline" "codepipeline" {
id       = "cloudtrail-monitoring"
name     = "cloudtrail-monitoring"
tags     = {}
~ stage {
~ name = "Development" -> "Upload_Image"
~ action {
~ configuration    = {
+ "EnvironmentVariables" = jsonencode(
[
+ {
+ name  = "IMAGE_TAG"
+ type  = "PLAINTEXT"
+ value = "#{SourceVariables.CommitId}-#{Timestamp.BUILD_TIMESTAMP}"
},
]
)
~ "ProjectName"          = "cloudtrail-monitoring-development" -> …
```
=> PSEC-1650 move cloudtrail-monitoring to dockerised publishing

main.tf, pipelines.tf
so we can receive alerts in slack
=> Send alerts to prod sns topic

modules/build_artifact_step/build.tf, modules/build_timestamp_step/codebuild.tf, modules/docker_deployment_step/codebuild.tf, modules/git_tag_step/codebuild.tf, modules/git_version_step/codebuild.tf, modules/pull_request_builder/codebuild.tf, modules/terraform_step/codebuild.tf, modules/update_task_definition_step/codebuild.tf, modules/upload_to_artifactory_step/codebuild.tf, modules/upload_to_ci_ecr_step/codebuild.tf, modules/zip_deployment_step/codebuild.tf, modules/zip_upload_step/codebuild.tf
=> PSEC-1985-update-codebuild-image

modules/pull_request_builder/buildspecs/monitor-aws-iam.yaml, pull_request_builder.tf
Add PR builder for monitor-aws-iam repo
=> PSEC-2062-monitor-aws-iam-pr-builder

.gitignore, .terraform.lock.hcl, modules/lambda_docker_pipeline_codestar_connection/README.md, modules/lambda_docker_pipeline_codestar_connection/build.tf, modules/lambda_docker_pipeline_codestar_connection/iam.tf, modules/lambda_docker_pipeline_codestar_connection/main.tf, modules/lambda_docker_pipeline_codestar_connection/pipeline.tf, modules/lambda_docker_pipeline_codestar_connection/variables.tf, pipelines.tf
First draft. Planned successfully, but apply not run yet.
=> PSEC-2210 Github v2 migration

modules/pipeline_common/github_webhook.tf
Added this to avoid a mass webhook re-create
=> PSEC-2210 Added lifecycle to ignore changes to the authentication block

ci/pipeline.tf
=> PSEC-2203-src-branch

scripts/run.sh
=> PSEC-2203-run-script

bootstrap/backend.tf, live/backend.tf
Bootstrap component TF state encryption enabled
=> PSEC-2203-bootstrap-enable-state-encryption

ci/data.tf, ci/outputs.tf, live/main.tf, live/pipelines.tf
Decommission ci_alerts_for_${environment} sns topic, which have been replaced by an SNS topic, i.e. 'ci-alerts'
=> PSEC-2203-cleanup-sns-topics

bootstrap/.terraform.lock.hcl, bootstrap/s3.tf, modules/access_logs_bucket/main.tf, modules/access_logs_bucket/variables.tf
access logs bucket module refactored to ensure access to all tf-admin roles
=> PSEC-2203-access-logs-bucket

bootstrap/s3.tf, live/main.tf
Clean up RoleTerraformProvisioner access
=> PSEC-2203-cleanup-tf-provisioner-role

bootstrap/data.tf, bootstrap/kms.tf, bootstrap/providers.tf
Brought kms inline wiith proposed policy
=> PSEC-2210 Added default tags and kms changes

live/.terraform.lock.hcl, live/ecr_repositories.tf, live/pipelines.tf, live/pull_request_builder.tf, modules/pull_request_builder/buildspecs/aws-users-manager.yaml
CI/CD pipeline for aws-users-manager
=> PSEC-2221-aws-users-manager

modules/upload_to_ci_ecr_step/assets/upload-to-ecr.yaml
tag container image with 'latest' tag
=> PSEC-2221-container-image-latest-tag

modules/renovatebot_pipeline/buildspecs/buildspec.yaml.tftpl, modules/renovatebot_pipeline/iam.tf
Added path fix
Added permissions fix
=> PSEC-2231 Commit signing config path and iam fix

modules/upload_to_ci_ecr_step/iam.tf
=> PSEC-2258-missing-perm

modules/upload_to_ci_ecr_step/assets/upload-to-ecr.yaml
Fixed conditional in buildspec of upload-to-ecr build stage
=> PSEC-2258-fix-upload-to-ecr

modules/pull_request_builder/buildspecs/platsec_terraform_plan.yaml
platsec-terraform pr-builder buildspec updated to use terragrunt commands
=> PSEC-1793-platsec-terraform-tg-migration

modules/pull_request_builder/buildspecs/platsec_terraform_plan.yaml
platsec-terraform pr-builder buildspec updated to use run.sh script in the source repo
=> PSEC-1793-platsec-terraform-tg-migration-2

live/ecr_repositories.tf, live/pipelines.tf, live/pull_request_builder.tf, modules/pull_request_builder/buildspecs/prowler-scan-enqueuer.yaml
CI/CD config for prowler-scan-enqueuer lambda
=> PSEC-2363-prowler-scan-enqueuer-cicd

live/pull_request_builder.tf, modules/pull_request_builder/buildspecs/bitwarden-manager.yaml
Creating a new pr builder in codebuild to migrate away from MDTP Jenkins
=> PSEC-2328-bitwarden-manager-pr-builder

live/pull_request_builder.tf, modules/pull_request_builder/buildspecs/aws-scanner.yaml
Creating a new pr builder in codebuild to migrate away from MDTP Jenkins
=> PSEC-2328-aws-scanner-pr-builder

modules/pull_request_builder/buildspecs/aws-scanner.yaml
Update env var required for platsec-aws-scanner pr-builder job
=> PSEC-2328-aws-scanner-pr-builder-2

live/pull_request_builder.tf, modules/pull_request_builder/buildspecs/cloudtrail-monitoring.yaml, modules/pull_request_builder/buildspecs/compliance-alerting.yaml, modules/pull_request_builder/buildspecs/compliance-dataviz.yaml
Creating new pr builders in codebuild to migrate away from MDTP Jenkins
=> PSEC-2328-pr-builders

modules/pull_request_builder/buildspecs/compliance-alerting.yaml
=> PSEC-2328-fix-typo

bootstrap/.terraform.lock.hcl, ci/.terraform.lock.hcl, modules/pipeline_common/s3.tf, modules/pipeline_common/variables.tf, modules/pull_request_builder/s3.tf, modules/pull_request_builder/variables.tf
enabling glacier transition after 7 days on pr_builder_bucket and codepipeline_bucket
https://jira.tools.tax.service.gov.uk/browse/PSEC-2383
=> PSEC-2383 enable glacier transition after 7 days on buckets 

bootstrap/s3.tf
https://jira.tools.tax.service.gov.uk/browse/PSEC-2388
=> PSEC-2388 enable RoleProwlerScanner to read_roles, list_roles & metadata_read_roles for s3 bucket

modules/networking-new/ci_security_group.tf, modules/pipeline_common/s3.tf
The change allows for the Prowler Scanner to access the CI buckets
=> PSEC-2566: Add ReadOnly ProwlerScanner Access

modules/lambda_docker_pipeline/pipeline.tf
Moved PIPELINE_NAME env var to the correct codepipeline action
=> PSEC-2577-fix-env-var-lambda-docker-pipeline
